sudo: required

services:
  - docker

script:
  - docker build -t alexquast/cordova-grunt .
  - docker run alexquast/cordova-grunt /bin/sh -c "cordova create test && cd test && cordova platform add android && cordova build android && grunt && bower && git"
